<?php
defined( 'ABSPATH' ) || exit;
$book_id = isset( $book_id ) ? absint( $book_id ) : 0;
?>
<section class="space-y-8" data-balance-beacon-settings data-book-id="<?php echo esc_attr( $book_id ); ?>">
<h1 class="text-2xl font-bold">設定</h1>
<div class="rounded-lg bg-white p-6 shadow"><h2 class="mb-4 text-xl font-semibold">帳戶管理</h2><div id="balance-accounts-list" class="mb-6 space-y-2"></div>
<form id="balance-account-form" class="grid gap-3 md:grid-cols-2"><input type="hidden" name="edit_id"><input type="text" name="name" required class="rounded border p-2" placeholder="帳戶名稱"><input type="number" name="initial_balance" value="0" step="0.01" class="rounded border p-2" placeholder="初始金額"><select name="group_id" class="rounded border p-2"><option value="">選擇帳戶群組</option></select><select name="currency_id" class="rounded border p-2"><option value="">選擇幣別</option></select><input type="hidden" name="account_group" value="cash"><input type="hidden" name="currency" value="TWD"><div id="credit-card-fields" class="hidden grid gap-3 rounded border border-blue-100 bg-blue-50 p-3 md:col-span-2 md:grid-cols-2"><label>結帳日<input type="number" name="statement_date" min="1" max="31" class="rounded border p-2"></label><label>繳款日<input type="number" name="payment_date" min="1" max="31" class="rounded border p-2"></label></div><label><input type="checkbox" name="is_active" value="1" checked> 啟用此帳戶</label><label><input type="checkbox" name="default_confirmed" value="1"> 套用預設入帳</label><label class="md:col-span-2"><input type="checkbox" name="is_hidden" value="1"> 隱藏此帳戶，不在新增交易的選單中顯示</label><button type="submit" class="rounded bg-blue-600 px-4 py-2 text-white md:col-span-2">新增帳戶</button></form></div>
<div class="rounded-lg bg-white p-6 shadow"><h2 class="mb-4 text-xl font-semibold">帳戶群組管理</h2><div id="groups-list" class="mb-6 space-y-2"></div><form id="account-group-form" class="grid gap-3 md:grid-cols-3"><input type="hidden" name="edit_id"><input type="text" name="name" required class="rounded border p-2 md:col-span-2" placeholder="群組名稱"><button type="submit" class="rounded bg-blue-600 px-4 py-2 text-white">新增群組</button></form></div>
<div class="rounded-lg bg-white p-6 shadow"><h2 class="mb-4 text-xl font-semibold">幣別管理</h2><div id="currencies-list" class="mb-6 space-y-2"></div><form id="currency-form" class="grid gap-3 md:grid-cols-5"><input type="hidden" name="edit_id"><input type="text" name="code" required maxlength="10" class="rounded border p-2" placeholder="代碼，例如 USD"><input type="text" name="name" required class="rounded border p-2" placeholder="名稱，例如 美金"><input type="text" name="symbol" class="rounded border p-2" placeholder="符號，例如 $"><input type="number" name="decimals" min="0" max="8" value="2" required class="rounded border p-2"><button type="submit" class="rounded bg-blue-600 px-4 py-2 text-white">新增幣別</button></form></div>
<?php $sections = array('category'=>array('分類管理','balance-categories-list','balance-category-form','分類名稱'),'tag'=>array('標籤管理','tag-list-container','tag-form','標籤名稱'),'member'=>array('成員管理','member-list-container','member-form','成員名稱'),'store'=>array('商店管理','store-list-container','store-form','商店名稱')); foreach($sections as $type=>$s): ?><div class="rounded-lg bg-white p-6 shadow"><h2 class="mb-4 text-xl font-semibold"><?php echo esc_html($s[0]); ?></h2><div id="<?php echo esc_attr($s[1]); ?>" class="mb-6 space-y-2"></div><form id="<?php echo esc_attr($s[2]); ?>" class="grid gap-3 md:grid-cols-4"><input type="hidden" name="edit_id"><input type="text" name="name" required class="rounded border p-2 md:col-span-2" placeholder="<?php echo esc_attr($s[3]); ?>"><?php if($type==='category'): ?><select name="category_type" class="rounded border p-2"><option value="expense">支出</option><option value="income">收入</option></select><select name="parent_id" class="rounded border p-2"><option value="">無（主分類）</option></select><?php endif; ?><label><input type="checkbox" name="is_hidden" value="1"> 隱藏此項目</label><button type="submit" class="rounded bg-blue-600 px-4 py-2 text-white">新增</button></form></div><?php endforeach; ?></section>
