<?php
defined( 'ABSPATH' ) || exit;
final class Balance_Beacon_Assets {
	public function register() { add_action( 'wp_head', array( $this, 'tailwind' ) ); add_action( 'wp_enqueue_scripts', array( $this, 'enqueue' ) ); }
	private function has_shortcode() { $id = get_queried_object_id(); $content = $id ? (string) get_post_field( 'post_content', $id ) : ''; return $id && ( has_shortcode( $content, 'balance_transactions' ) || has_shortcode( $content, 'balance_settings' ) || has_shortcode( $content, 'balance_app' ) ); }
	public function tailwind() { if ( $this->has_shortcode() ) echo '<script src="https://cdn.tailwindcss.com"></script>' . "\n"; }
	public function enqueue() { if ( ! $this->has_shortcode() ) return; $config = array( 'apiUrl' => rest_url( 'balance-beacon/v1' ), 'nonce' => wp_create_nonce( 'wp_rest' ) ); $app = $this->page_has( 'balance_app' ); wp_register_script( 'balance-beacon-ui-utils', BALANCE_BEACON_URL . 'assets/js/ui-utils.js', array(), BALANCE_BEACON_VERSION, true ); wp_enqueue_script( 'balance-beacon-ui-utils' ); if ( $app ) { wp_enqueue_script( 'balance-beacon-app', BALANCE_BEACON_URL . 'assets/js/app.js', array( 'balance-beacon-ui-utils' ), BALANCE_BEACON_VERSION, true ); } if ( $app || $this->page_has( 'balance_transactions' ) ) { $h = 'balance-beacon-transactions'; wp_register_script( $h, BALANCE_BEACON_URL . 'assets/js/transactions.js', array( 'balance-beacon-ui-utils' ), BALANCE_BEACON_VERSION, true ); wp_localize_script( $h, 'BalanceBeaconConfig', $config ); wp_enqueue_script( $h ); } if ( $app || $this->page_has( 'balance_settings' ) ) { $h = 'balance-beacon-settings'; wp_register_script( $h, BALANCE_BEACON_URL . 'assets/js/settings.js', array( 'balance-beacon-ui-utils' ), BALANCE_BEACON_VERSION, true ); wp_localize_script( $h, 'BalanceBeaconConfig', $config ); wp_enqueue_script( $h ); } }
	private function page_has( $tag ) { $id = get_queried_object_id(); return $id && has_shortcode( (string) get_post_field( 'post_content', $id ), $tag ); }
}
